language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django16
    - TOX_ENV=py26-django16
    - TOX_ENV=py27-django15
    - TOX_ENV=py26-django15
    - TOX_ENV=py27-django14
    - TOX_ENV=py26-django14
    - TOX_ENV=py27-djangomaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py2.7-djangomaster

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
