language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py26-django16-drf24
    - TOX_ENV=py26-django16-drf30
    - TOX_ENV=py26-django16-drf31
    - TOX_ENV=py27-django16-drf24
    - TOX_ENV=py27-django16-drf24
    - TOX_ENV=py27-django16-drf30
    - TOX_ENV=py27-django16-drf31
    - TOX_ENV=py27-django17-drf24
    - TOX_ENV=py27-django17-drf24
    - TOX_ENV=py27-django17-drf30
    - TOX_ENV=py27-django17-drf31

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
